import Head from 'next/head';
import { useRouter } from 'next/router';

const DynamicPage = () => {
  const router = useRouter();

  const query = router.query.id;

  return (
    <div>
      <Head>
        <title>{query}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        Hi there I am a dynamic route: {query}
    </div>
  );
};

export default DynamicPage;
