import Head from 'next/head';

import Banner from '@/components/banner';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const handleBannerBtnClick = () => {
    console.log('handleBannerBtnClick');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleBannerBtnClick}
        />
      </main>
    </div>
  );
}
